/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function convertBgraToRgb(bgraData: Uint8Array, width: number, height: number): Uint8Array

export declare function convertNv12ToGrayscale(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertNv12ToRgb(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertNv12ToRgba(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertRgbaToRgb(rgbaData: Uint8Array, width: number, height: number): Uint8Array

export declare function convertRgbToRgba(rgbData: Uint8Array, width: number, height: number): Uint8Array

export declare function convertYuvToGrayscale(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertYuvToRgb(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertYuvToRgba(frame: Buffer, width: number, height: number): Uint8Array

export declare function cropImage(frame: Uint8Array, inputWidth: number, inputHeight: number, channels: number, cropLeft: number, cropTop: number, cropWidth: number, cropHeight: number): Uint8Array

export declare function processImage(inputFrame: Uint8Array, inputWidth: number, inputHeight: number, inputFormat: number, outputFormat: number, cropTop: number, cropLeft: number, cropWidth: number, cropHeight: number, resizeWidth: number, resizeHeight: number): Uint8Array

export declare function processImageDebug(inputFrame: Uint8Array, inputWidth: number, inputHeight: number, inputFormat: number, outputFormat: number, cropTop: number, cropLeft: number, cropWidth: number, cropHeight: number, resizeWidth: number, resizeHeight: number, outputDir: string, prefix: string): Uint8Array

export declare function resizeAndCrop(inputFrame: Uint8Array, inputWidth: number, inputHeight: number, channels: number, cropLeft: number, cropTop: number, cropWidth: number, cropHeight: number, outputWidth: number, outputHeight: number): Uint8Array

export declare function resizeImage(frame: Uint8Array, inputWidth: number, inputHeight: number, channels: number, outputWidth: number, outputHeight: number): Uint8Array
