/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function convertBgraToRgb(bgraData: Uint8Array, width: number, height: number): Uint8Array

export declare function convertNv12ToGrayscale(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertNv12ToRgb(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertNv12ToRgba(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertRgbaToRgb(rgbaData: Uint8Array, width: number, height: number): Uint8Array

export declare function convertRgbToRgba(rgbData: Uint8Array, width: number, height: number): Uint8Array

export declare function convertYuvToGrayscale(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertYuvToRgb(frame: Buffer, width: number, height: number): Uint8Array

export declare function convertYuvToRgba(frame: Buffer, width: number, height: number): Uint8Array

export declare function cropImage(frame: Uint8Array, inputWidth: number, inputHeight: number, channels: number, cropLeft: number, cropTop: number, cropWidth: number, cropHeight: number): Uint8Array

export declare function processImage(inputFrame: Uint8Array, inputWidth: number, inputHeight: number, inputFormat: number, outputFormat: number, cropTop: number, cropLeft: number, cropWidth: number, cropHeight: number, resizeWidth: number, resizeHeight: number): Uint8Array

export declare function processImageDebug(inputFrame: Uint8Array, inputWidth: number, inputHeight: number, inputFormat: number, outputFormat: number, cropTop: number, cropLeft: number, cropWidth: number, cropHeight: number, resizeWidth: number, resizeHeight: number, outputDir: string, prefix: string): Uint8Array

export declare function resizeAndCrop(inputFrame: Uint8Array, inputWidth: number, inputHeight: number, channels: number, cropLeft: number, cropTop: number, cropWidth: number, cropHeight: number, outputWidth: number, outputHeight: number): Uint8Array

export declare function resizeImage(frame: Uint8Array, inputWidth: number, inputHeight: number, channels: number, outputWidth: number, outputHeight: number): Uint8Array
